import "./globals.css";
import { Provider } from "@/components/ui/provider"
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/authContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AuthProvider>
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
